### ISSUE TITLE
Feature - Mark All As Read

### ISSUE THREAD

**Issue by mikeriley** [spencerwi/cliflux#16]
Nice job with the app. I really like how clean and easy it is to use. One time saving feature I would like to see in a future release is a 'Mark All As Read' option, assigned to the 'a' key, that quickly marks all articles as read and auto-refreshes the main Unread Entries screen. Hopefully such an enhancement would be fairly easy to implement.

**Comment by spencerwi** [comment]
Thanks! I've added this in v1.5.0, releasing today. Hit `a` to trigger it.

**Comment by mikeriley** [comment]
Wow, that was quick! Works great - thank you! Just an FYI, you might want to document the 'a' key assignment on the '?' keyboard help screen too.
