### ISSUE TITLE
feature: save articles

### ISSUE THREAD

**Issue by slundi** [spencerwi/cliflux#9]
hello,

Can we have the feature to send the article to Send articles to [Telegram](https://telegram.org/), [Shaarli](https://github.com/shaarli/Shaarli), [Shiori](https://github.com/go-shiori/shiori), [Matrix](https://matrix.org/), [Apprise](https://github.com/caronc/apprise), [Pinboard](https://pinboard.in/), [Instapaper](https://www.instapaper.com/), [Pocket](https://getpocket.com/), [Wallabag](https://www.wallabag.org/), [Linkding](https://github.com/sissbruecker/linkding), [Espial](https://github.com/jonschoning/espial), [Notion](https://www.notion.so/), [Readwise Reader](https://readwise.io/read) or [Nunux Keeper](https://keeper.nunux.org/)?
The API looks available: https://miniflux.app/docs/api.html#endpoint-save-entry

And also toggle entry bookmark: https://miniflux.app/docs/api.html#endpoint-toggle-bookmark

**Comment by spencerwi** [comment]
Sounds like a solid idea. It might be a little confusing to differentiate bookmarking vs. saving vs. starring, but honestly, that's a Miniflux thing, and this would just be adding support for what's already in Miniflux. Time permitting, I'll take a crack at this when I can.

**Comment by slundi** [comment]
Hi,
It is just to call the Miniflux API on:
- https://miniflux.app/docs/api.html#endpoint-save-entry (maybe Ctrl+S)
- the starred attribute, I think it is here: https://miniflux.app/docs/api.html#endpoint-toggle-bookmark (maybe Ctrl+D like in web browsers)

**Comment by spencerwi** [comment]
>the starred attribute

cliflux already supports this one: https://github.com/spencerwi/cliflux/blob/8795c38b3962511a395fec5c12d1a9171d1e08aa/src/ui/components/keyboard_help.rs#L74

The other endpoint for  "save entry" (which actually seems to be a "share to other services" endpoint) seems relatively-straightforward to add. The difficulty there would just be UX; there's no persistent attribute on any given entry that tells you "this has been shared to another service", and it's not clear how to signal success or errors.

**Comment by spencerwi** [comment]
I know it's taken me forever to get back to this, but I implemented an initial version of the "save to external services" action in v1.5.0, releasing today.
